Migrated to new reporter.
arquillian/arquillian-cube-q pull request #26
Opened 2017-03-13 09:12 UTC by dipak-pawar

#### Short description of what this resolves:
Added new reporter integration

#### Changes proposed in this pull request:

- Added new reporter integration
- Updated mvn dependencies to use latest stable versions.

**Fixes**: #25

2017-03-17 10:31 UTC, MatousJobanek requested changes

2017-03-17 10:31 UTC, MatousJobanek commented on pom.xml
> +        <version.arquillian.reporter>0.0.2</version.arquillian.reporter>
please add to this commit only relevant changes - updates of junit or arquillian-core versions put into a separate commit

2017-03-17 10:31 UTC, MatousJobanek commented on reporter/src/main/java/org/arquillian/cube/q/recorder/TakeNetworkChaosInformation.java
> +                .addEntry(fileEntry)
at this point, I would expect addKeyValueEntry where the key is some kind of description what the file contains etc... As a value you can use any Entry, so also FileEntry

2017-03-21 08:09 UTC, bartoszmajsak commented
- [ ] Resolve merge conflicts
- [ ] Update Cube

2017-03-22 05:41 UTC, bartoszmajsak approved these changes
Just one small thing. Other than that LGTM

2017-03-22 05:41 UTC, bartoszmajsak commented on pom.xml
> +        <version.arquillian.reporter>0.0.2</version.arquillian.reporter>
I believe there is `0.0.3` out in the wild already.

2017-03-22 08:33 UTC, lordofthejars approved these changes

2017-03-24 15:23 UTC, MatousJobanek commented
How about the versions in the main pom - shouldn't be the version updates part of another commit/PR? Or do we somehow depend on the updates in this PR?

2017-03-24 15:27 UTC, dipak-pawar commented
@MatousJobanek We depends on new version of assertJ & Cube for this PR.

2017-03-24 15:28 UTC, MatousJobanek commented
OK, cool. Then LGTM :-)
Thanks @dipak-pawar

2017-03-24 15:28 UTC, MatousJobanek approved these changes

2017-03-24 15:35 UTC, merged